// <auto-generated />
using System;
using CHSYesWebApp.Data;
using CHSYesWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CHSYesWebApp.Migrations.ServiceForm
{
    [DbContext(typeof(CHSYesWebAppContext))]
    partial class ServiceFormContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.2-rtm-30932")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CHSYesWebApp.Models.ServiceForm", b =>
                {
                    b.Property<int>("ServiceFormId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("HourOfService");

                    b.Property<string>("OrganizationName");

                    b.Property<string>("OrganizationPhone");

                    b.Property<string>("OrganizationStreetAddress");

                    b.Property<string>("OrganizationWebSite");

                    b.Property<string>("OwnerID");

                    b.Property<string>("ParentSignature");

                    b.Property<bool>("RewardedForService");

                    b.Property<DateTime>("ServiceDate");

                    b.Property<string>("ServiceDescription");

                    b.Property<string>("SponsorEmail");

                    b.Property<string>("SponsorName");

                    b.Property<int>("Status");

                    b.Property<string>("StudentSignature");

                    b.HasKey("ServiceFormId");

                    b.ToTable("ServiceForm");
                });
#pragma warning restore 612, 618
        }
    }
}
